CREATE TABLE `comments` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`text` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`date_create` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
